POST http://localhost:8080/queries/
Content-Type: application/json

{
  "query": "ListVarieties",
  "data": {
    "speciesKey": "tomato"
  }
}
###

POST http://localhost:8080/queries/
Content-Type: application/json

{
  "query": "ListSpecies",
  "data": {

  }
}
###

POST http://localhost:8080/queries/
Content-Type: application/json

{
  "query": "GetSpecies",
  "data": {
    "key": "tomato"
  }
}
###
POST http://localhost:8080/queries/
Content-Type: application/json

{
  "query": "GetVariety",
  "data": {
    "key": "pea",
    "id": "madonna"
  }
}
###
POST http://localhost:8080/commands/
Content-Type: application/json

{
  "command": "CreateCropPlan",
  "data": {
    "bedId": "bed-123",
    "name": "Весенние томаты 2024",
    "speciesKey": "tomato",
    "varietyId": "bull_heart",
    "seasonId": "season-1",
    "plantingDate": "2024-03-15T00:00:00Z",
    "assignedTo": "user-1"
  }
}

###

POST http://localhost:8080/queries/
Content-Type: application/json

{
  "query": "ListCropPlan",
  "data": {
    "status": "draft"
  }
}
###
POST http://localhost:8080/queries/
Content-Type: application/json

{
  "query": "GetCurrentPhenology",
  "data": {
    "plan_id": "0198ad1a-f374-494f-afc0-087662b0b158"
  }
}

###
POST http://localhost:8080/queries/
Content-Type: application/json

{
  "query": "GetCropPlan",
  "data": {
    "planId": "dfb2500b-6fd7-4be3-b253-5eca2ceea27b"
  }
}

###

POST http://localhost:8080/queries/
Content-Type: application/json

{
  "query": "GetPlanStatistics",
  "data": {
    "planId": "dfb2500b-6fd7-4be3-b253-5eca2ceea27b"
  }
}

###
POST http://localhost:8080/commands/
Content-Type: application/json

{
  "command": "SkipStage",
  "data": {
    "plan_id": "plan-123",
    "stage_id": "stage-456",
    "reason": "Погодные условия не позволяют выполнить"
  }
}

###
POST http://localhost:8080/commands/
Content-Type: application/json

{
  "command": "CompleteStage",
  "data": {
    "plan_id": "plan-123",
    "stage_id": "stage-456"
  }
}

###
POST http://localhost:8080/commands/
Content-Type: application/json

{
  "command": "StartStage",
  "data": {
    "plan_id": "plan-123",
    "stage_id": "stage-456",
    "current_bbch": 61
  }
}

###

POST http://localhost:8080/commands/
Content-Type: application/json

{
  "command": "AddStage",
  "data": {
    "plan_id": "plan-123",
    "name": "Обработка от вредителей",
    "type": "protection",
    "description": "Опрыскивание от тли",
    "bbch_start": 50,
    "bbch_end": 69,
    "order": 5
  }
}

###
POST http://localhost:8080/commands/
Content-Type: application/json

{
  "command": "ActivateCropPlan",
  "data": {
    "plan_id": "plan-123"
  }
}


###

POST http://localhost:8080/commands/
Content-Type: application/json

{
  "command": "CancelCropPlan",
  "data": {
    "plan_id": "plan-123",
    "reason": "Изменение севооборота"
  }
}

###

