### commands
POST http://localhost:8080/commands/
Content-Type: application/json

{
  "command": "CreateFacility",
  "data": {
    "id": "181643d1-7080-4d24-b3ab-84767d7a1213",
    "name": "Теплица 1",
    "type": "FIELD",
    "length": 100,
    "width": 50
  }
}

###


POST http://localhost:8080/commands/
Content-Type: application/json

{
  "command": "AddBed",
  "data": {
    "facility_id": "781643dc-7080-4d24-b3ab-84767d7a1217",
    "name": "Грядка A1",
    "length": 10,
    "width": 1.2
  }
}


### queries

POST http://localhost:8080/queries/
Content-Type: application/json

{
  "query": "GetFacilityOverview",
  "data": {
    "facility_id": "781643dc-7080-4d24-b3ab-84767d7a1217"
  }
}
###

POST http://localhost:8080/queries/
Content-Type: application/json

{
  "query": "GetFacilitiesList",
  "data": {
  }
}