### commands
POST http://localhost:8080/commands/
Content-Type: application/json

{
  "command": "CreateField",
  "data": {
    "name": "Поле 3",
    "geom" : {
      "type": "Polygon",
      "coordinates": [
        [
          [
            30.01688506454229,
            45.9046543105274
          ],
          [
            30.02165973186493,
            45.90500076497716
          ],
          [
            30.021628215909004,
            45.905195105146134
          ],
          [
            30.01937616616488,
            45.905034827048745
          ],
          [
            30.016832761466503,
            45.90482508834458
          ],
          [
            30.01688506454229,
            45.9046543105274
          ]
        ]
      ]
    }
  }
}

###

### commands
POST http://localhost:8080/commands/
Content-Type: application/json

{
  "command": "CreateGreenhouse",
  "data": {
    "name": "Теплица 4",
    "length": 12,
    "width": 4,
    "geom" : {
      "type": "Point",
      "coordinates": [30.0162001, 45.9007626]
    }
  }
}
###

POST http://localhost:8080/commands/
Content-Type: application/json

{
  "command": "CreateFieldBlock",
  "data": {
    "parent_id": "5f53eef2-faf3-4b01-b5e7-c1da6152de5c",
    "name": "Участок 3",
    "geom" : {
      "type": "Polygon",
      "coordinates": [
        [
          [
            30.01688506454229,
            45.9046543105274
          ],
          [
            30.02165973186493,
            45.90500076497716
          ],
          [
            30.021628215909004,
            45.905195105146134
          ],
          [
            30.01937616616488,
            45.905034827048745
          ],
          [
            30.016832761466503,
            45.90482508834458
          ],
          [
            30.01688506454229,
            45.9046543105274
          ]
        ]
      ]
    }
  }
}

###

POST http://localhost:8080/commands/
Content-Type: application/json

{
  "command": "CreateBed",
  "data": {
    "name": "Грядка A1",
    "length": 10,
    "width": 1.2,
    "parent_id": "",
    "geom" : {"type":  "Points", "coordinates": [45.3, 23.3]}
  }
}


### queries

POST http://localhost:8080/queries/
Content-Type: application/json

{
  "query": "GetFacilityOverview",
  "data": {
    "facility_id": "781643dc-7080-4d24-b3ab-84767d7a1217"
  }
}
###

POST http://localhost:8080/queries/
Content-Type: application/json

{
  "query": "GetFacilitiesList",
  "data": {
  }
}