### commands
POST http://localhost:8080/commands/
Content-Type: application/json

{
  "command": "CreatePhysicalObject",
  "data": {
    "type": "greenhouse",
    "name": "Теплица 4awtbgyhnw",
    "length": 12,
    "width": 4,
    "owner_id": "d940abb7-b622-4b89-a0f0-9b99abdbd860",
    "geometry" : {
      "type": "Point",
      "coordinates": [30.0162001, 45.9007626]
    }
  }
}
###

POST http://localhost:8080/commands/
Content-Type: application/json

{
  "command": "CreatePhysicalObject",
  "data": {
    "type": "field",
    "name": "Участок sewfgu",
    "soil_type": "Чернозём",
    "geometry" : {
      "type": "Polygon",
      "coordinates": [
        [
          [
            30.05152512341738,
            45.90452692673153
          ],
          [
            30.052362643182278,
            45.89954309793805
          ],
          [
            30.054328702390194,
            45.89973605726784
          ],
          [
            30.056433230638508,
            45.89984875267262
          ],
          [
            30.056634396314617,
            45.90127154164979
          ],
          [
            30.056862048804764,
            45.90266559683004
          ],
          [
            30.057584568858147,
            45.90515847685902
          ],
          [
            30.053597800433632,
            45.904893212682424
          ],
          [
            30.053620599210262,
            45.90472780104589
          ],
          [
            30.05152512341738,
            45.90452692673153
          ]
        ]
      ]
    }
  }
}

###
POST http://localhost:8080/commands/
Content-Type: application/json

{
  "command": "CreateCropType",
  "data": {
    "name": "Пшеница",
    "category": "cereal",
    "description": "Озимая мягкая пшеница",
    "is_perennial": false
  }
}

###

POST http://localhost:8080/commands/
Content-Type: application/json

{
  "command": "CreateVariety",
  "data": {
    "crop": "Пшеница",
    "name": "Мироновскаяяц ",
    "description": "Озимая мягкая пшеница, устойчива к засухе",
    "vegetation_days": "110..130",
    "yield_potential": "10..130",
    "recommended_regions": ["Центральный", "Центрально-Черноземный"],
    "is_active": true
  }
}

###

POST http://localhost:8080/commands/
Content-Type: application/json

{
  "command": "CreateCropPlan",
  "data": {
    "crop_type_id": "e3db564e-c6e6-47c7-aa90-a84cdef1c846",
    "variety_id": "bc6f1c3a-ff7e-467a-9870-7120fa51775a",
    "name": "Интенсивная технология кабачка",
    "duration": 120,
    "description": "План с повышенными нормами удобрений",
    "created_by": "user-123"
  }
}

###

POST http://localhost:8080/commands/
Content-Type: application/json

{
  "command": "AddStage",
  "data": {
    "plan_id": "42350992-46fc-4ff4-83e9-1581b4e805c1",
    "order": 1,
    "name": "Всходы",
    "duration": 10,
    "min_temp": 5,
    "max_temp": 20,
    "optimal_temp": 12,
    "water_per_day": 1.5
  }
}

###


POST http://localhost:8080/commands/
Content-Type: application/json

{
  "command": "CreateSeason",
  "data": {
    "created_by": "2026",
    "end_date": "2023-01-14",
    "start_date": "2023-01-06",
    "name": "Всходы"

  }
}
### queries

POST http://localhost:8080/queries/
Content-Type: application/json

{
  "query": "ListObjects",
  "data": {
  }
}
###

POST http://localhost:8080/queries/
Content-Type: application/json

{
  "query": "GetFacilitiesList",
  "data": {
  }
}