POST http://localhost:8080/api/commands/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiYjhmYWE5MzktN2RhNy00NzA2LThiNjAtMmQ1NjMyNzYwMDBkIiwidXNlcm5hbWUiOiJzaGFsYXNoIiwiZW1haWwiOiJ0ZXN0QHRlc3QucnUiLCJyb2xlIjoid29ya2VyIiwiaXNzIjoiaG9tZS1zZXJ2aWNlcyIsImV4cCI6MTc3Njk3MTQ2OCwiaWF0IjoxNzc2ODg1MDY4fQ.TmNBxJ3FhT00fi_NVbg2lLjaCTg9-1f5IMzks6jPxZY

{
  "command": "CreateObject",
  "data": {
    "type": "greenhouse",
    "name": "shalasawdadawdawdh",
    "attributes": {
      "length": 12,
      "width": 4
    },
    "geometry": {
      "type": "Point",
      "coordinates": [
        30.0162001,
        45.9007626
      ]
    }
  }
}

###

POST http://localhost:8080/commands/
Content-Type: application/json

{"command":"DeleteObject","data":{"id":"58066c8c-2ebb-4ddb-a8cd-f182cd158ba4"}}

###

POST http://localhost:8080/commands/
Content-Type: application/json

{
  "command": "CreatePhysicalObject",
  "data": {
    "name": "Новое объект",
    "type": "field",
    "geometry": {
      "coordinates": [
        [
          [
            30.028455288736637,
            45.90258173424232
          ],
          [
            30.040468233823503,
            45.90186519474889
          ],
          [
            30.025537859215177,
            45.893265999496606
          ],
          [
            30.028455288736637,
            45.90258173424232
          ]
        ]
      ],
      "type": "Polygon"
    },
    "area": 49.047392534980986,
    "attributes": {
      "width": 1155.483543964361,
      "length": 1035.8638724837822
    }
  }
}

###
POST http://localhost:8080/commands/
Content-Type: application/json

{
  "command": "CreateCropType",
  "data": {
    "name": "Пшеница",
    "category": "cereal",
    "description": "Озимая мягкая пшеница",
    "is_perennial": false
  }
}

###

POST http://localhost:8080/commands/
Content-Type: application/json

{
  "command": "CreateVariety",
  "data": {
    "crop": "Пшеница",
    "name": "Мироновскаяяц ",
    "description": "Озимая мягкая пшеница, устойчива к засухе",
    "vegetation_days": "110..130",
    "yield_potential": "10..130",
    "recommended_regions": [
      "Центральный",
      "Центрально-Черноземный"
    ],
    "is_active": true
  }
}

###

POST http://localhost:8080/commands/
Content-Type: application/json

{
  "command": "CreateCropPlan",
  "data": {
    "crop_type_id": "e3db564e-c6e6-47c7-aa90-a84cdef1c846",
    "variety_id": "bc6f1c3a-ff7e-467a-9870-7120fa51775a",
    "name": "Интенсивная технология кабачка",
    "duration": 120,
    "description": "План с повышенными нормами удобрений",
    "created_by": "user-123"
  }
}

###

POST http://localhost:8080/commands/
Content-Type: application/json

{
  "command": "AddStage",
  "data": {
    "plan_id": "42350992-46fc-4ff4-83e9-1581b4e805c1",
    "order": 1,
    "name": "Всходы",
    "duration": 10,
    "min_temp": 5,
    "max_temp": 20,
    "optimal_temp": 12,
    "water_per_day": 1.5
  }
}

###


POST http://localhost:8080/commands/
Content-Type: application/json

{
  "command": "CreateSeason",
  "data": {
    "endDate": "2023-01-14",
    "startDate": "2023-01-06",
    "name": "Всходы",
    "status": "planning"
  }
}

### queries

POST http://localhost:8080/queries/
Content-Type: application/json

{
  "query": "GetPhysicalObjects",
  "data": {
    "type": "plot"
  }
}

###

POST http://localhost:8080/queries/
Content-Type: application/json

{
  "query": "GetCurrentFarm",
  "data": {
  }
}
###

POST http://localhost:8080/queries/
Content-Type: application/json

{
  "query": "ListSeasons",
  "data": {
  }
}

###

POST http://localhost:8080/queries/
Content-Type: application/json

{"command":"GetObjects","data":{"farmId":"41ff5034-51fb-4dd9-a39a-2a2d8c76a77a"}}

###

POST http://localhost:8080/queries/
Content-Type: application/json

{
  "query": "GetCropTypes",
  "data": {
    "id": "0603a466-b3a9-465a-a12e-a767ca86c625"
  }
}

###

POST http://localhost:8080/queries/
Content-Type: application/json

{"query":"GetVarieties","data":{"cropTypeId":"0603a466-b3a9-465a-a12e-a767ca86c625"}}

###

POST http://localhost:8080/queries/
Content-Type: application/json

{
  "query": "GetCategories",
  "data": {
  }
}

###

POST http://localhost:8080/queries/
Content-Type: application/json

{
  "query": "GetCropPlans",
  "data": {
    "id": "bd917c5d-1b69-45f7-be92-8e288efd9a4e"
  }
}

###

POST http://localhost:8080/queries/
Content-Type: application/json

{
  "query": "GetCultivationAreas",
  "data": {}
}

###

POST http://localhost:8080/queries/
Content-Type: application/json

{
  "query": "GetCultivationAreas",
  "data": {
    "id": "015c2bd7-105d-4124-99bb-404a2a74c846"
  }
}

###

POST http://localhost:8080/queries/
Content-Type: application/json

{
    "query": "SearchVarieties",
    "data": {
        "species_key": "tomato",
        "growing_type": "greenhouse",
        "season": "spring",
        "max_days_to_maturity": 100,
        "limit": 10
    }
}