POST http://localhost:8080/api/queries/
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
      "query": "getSeasons",
  "data": {}
}
###

POST http://localhost:8080/api/queries/
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "query": "getCrops",
  "data": {

  }
}
###

POST http://localhost:8080/api/queries/
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "query": "getVarieties",
  "data": {
    "cropKey": "eggplant"
  }
}
###


###
POST http://localhost:8080/api/queries/
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "query": "getVarieties",
  "data": {
    "id": "28a9f113-04dc-49f1-8355-65a0c6733847"
  }
}