POST http://localhost:8080/api/queries/
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "query": "getCrops",
  "data": {

  }
}
###

POST http://localhost:8080/api/queries/
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "query": "getVarieties",
  "data": {
    "cropKey": "eggplant"
  }
}
###


###
POST http://localhost:8080/queries/
Content-Type: application/json
Authorization: Bearer {{jwt_token}}

{
  "query": "GetVarieties",
  "data": {
    "id": "madonna"
  }
}